export const features = {
    hypertension: 'Hypertension',
    heart_disease: 'Heart Disease',
    average_glucose_level: 'Average Glucose Level',
    smoking_status: 'Smoking Status',
    chest_pain_type: 'Chest Pain Type',
    resting_electrocardiographic_result: 'Resting Electrocardiographic Result',
    maximum_heart_rate_achieved: 'Maximum Heart Rate Achieved',
    exercise_induced_angina: 'Exercise Induced Angina',
    previous_peak: 'Previous Peak',
    slope: 'Slope',
    major_coronary_arteries_number: 'Major Coronary Arteries Number',
    thalium_stress_test_result: 'Thalium Stress Test Result',
    smoking: 'Smoking Status',
    drank_alcohol: 'Drank Alcohol',
    stroke: 'Stroke',
    walking_difficulty: 'Walking Difficulty',
    diabetic: 'Diabetic',
    physical_activity: 'Physical Activity',
    general_health: 'General Health',
    asthma: 'Asthma',
    kidney_disease: 'Kidney Disease',
    skin_cancer: 'Skin Cancer',
    plasma_glucose_concentration: 'Plasma Glucose Concentration',
    diastolic_blood_pressure: 'Diastolic Blood Pressure',
    triceps_skin_fold_thickness: 'Triceps Skin Fold Thickness',
    two_hour_insulin: 'Insulin',
    diabetes_pedigree_function: 'Diabetes Pedigree Function',
    birth_date: 'Birth Date',
    gender: 'Gender',
    weight: 'Weight',
    height: 'Height',
    ever_married: 'Marriage History',
    work_type: 'Job Type',
    residence_type: 'Residence Type',
    pregnancy_count: 'Pregnancy Count',
    age: 'Age',
    age_category: 'Age Category',
    bmi: 'BMI',
}