# Generated by Django 4.2.13 on 2024-06-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_diabetesmellitusprediction_prediction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetesmellitusprediction',
            name='triceps_skin_fold_thickness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diabetesmellitusprediction',
            name='two_hour_insulin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
